<a href="https://colab.research.google.com/github/Salciano/ShowcasePython/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#@title Transposition > NumPy > Libs + Vars

import numpy as np

print("In NumPy, scalars, vectors, matrices and tensors belong to the class type ndarray (n-dimensional arrays).")

print("\nHere we have 4 variables: scalar2, vector2, matrix2, tensor2.")

scalar2 = np.array( [1] )
print("\n1. scalar2:")
print(scalar2)
print(type(scalar2), scalar2.shape)

vector2 = np.array([1, 2, 3, 4])
print("\n2. vector2:")
print(vector2)
print(type(vector2), vector2.shape)

matrix2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]])
print("\n3. matrix2:")
print(matrix2)
print(type(matrix2), matrix2.shape)

tensor2 = np.array([
    [[1,2,3,4],
     [5,6,7,8]],

    [[9,10,11,12],
     [13,14,15,16]]])
print("\n4. tensor2:")
print(tensor2)
print(type(tensor2), tensor2.shape)


In NumPy, scalars, vectors, matrices and tensors belong to the class type ndarray (n-dimensional arrays).

Here we have 4 variables: scalar2, vector2, matrix2, tensor2.

1. scalar2:
[1]
<class 'numpy.ndarray'> (1,)

2. vector2:
[1 2 3 4]
<class 'numpy.ndarray'> (4,)

3. matrix2:
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'> (2, 4)

4. tensor2:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
<class 'numpy.ndarray'> (2, 2, 4)


In [3]:
#@title Transposition > NumPy > Vectors

print("\nIn NumPy, transposing a vector results in the same vector.")
print("As we can see, it does not transpose a row vector into a column vector or vice-versa.")
print("Untransposed vector2:" , vector2)
print("vector2.T):", np.transpose(vector2))
print("np.transpose(vector2):", np.transpose(vector2))

print("\nThere are different ways to go around this.")

print("The simplest one is to create the vector, as a 2D array, instead of a 1D Array:")
print("So, instead of:", vector2)
vector2 = np.array([ [1, 2, 3, 4]]) # instead of vector2 = np.array ([1, 2, 3, 4])
print("Insert extra brackets:", vector2)

print("\nAfter gaving it an extra dimension, it can be transposed:")
print("vector2.T:"), print(vector2.T)
print("np.transpose(vector2):"), print(np.transpose(vector2))

vector2 = np.array([1,2,3,4]) # restore vector2

print("\nOther ways to reshape vector2 into a column vector:")
print("vector2[:, None]"), print(vector2[:, None])
print(vector2[:, None].shape)
print("\nvector2.reshape(-1,1)"), print(vector2.reshape(-1, 1))
print(vector2.reshape(-1, 1).shape)
print("\nvector2[:, np.newaxis:"), print(vector2[:, np.newaxis], vector2[:, np.newaxis].shape)

print("However, these transforms the 1D (1-dimensional) array into a 2D array, as well:")

print("\nAlso, repeating vector2[:2, None] twice does not transpose it back into a 1D array. Instead, it turns it into a 3D array.")
vector2 = vector2[:, None]
print(vector2[:, None])
print(vector2[:, None].shape, type(vector2))

print("\nLets see what happens, if we transpose vector2, now.")
print("2D vector2:")
print(vector2)
print(vector2.shape)

print("\nvector2.T:")
print(vector2.T)
print(vector2.T.shape)

vector2 = np.array([1, 2, 3, 4]) # restore vector2

print("\nNow, lets refer to our 2D matrix2...")
print("2D matrix2")
print(matrix2)
print(matrix2.shape)
print("\nTrying this with on matrix2, also turns it into a 3D array:")
print("matrix2[:, None]")
print(matrix2[:, None])
print(matrix2[:, None].shape)



In NumPy, transposing a vector results in the same vector.
As we can see, it does not transpose a row vector into a column vector or vice-versa.
Untransposed vector2: [1 2 3 4]
vector2.T): [1 2 3 4]
np.transpose(vector2): [1 2 3 4]

There are different ways to go around this.
The simplest one is to create the vector, as a 2D array, instead of a 1D Array:
So, instead of: [1 2 3 4]
Insert extra brackets: [[1 2 3 4]]

After gaving it an extra dimension, it can be transposed:
vector2.T:
[[1]
 [2]
 [3]
 [4]]
np.transpose(vector2):
[[1]
 [2]
 [3]
 [4]]

Other ways to reshape vector2 into a column vector:
vector2[:, None]
[[1]
 [2]
 [3]
 [4]]
(4, 1)

vector2.reshape(-1,1)
[[1]
 [2]
 [3]
 [4]]
(4, 1)

vector2[:, np.newaxis:
[[1]
 [2]
 [3]
 [4]] (4, 1)
However, these transforms the 1D (1-dimensional) array into a 2D array, as well:

Also, repeating vector2[:2, None] twice does not transpose it back into a 1D array. Instead, it turns it into a 3D array.
[[[1]]

 [[2]]

 [[3]]

 [[4]]]
(4, 1, 1)

In [4]:
#@title Transposition > NumPy > Matrices, Tensors...

print("\nIn NumPy, we can transpose matrices and tensors. For example, matrix2 can be transposed, using matrix2.T or numpy.transpose(matrix2)")

#matrix2 = matrix2.T
print("\nHere is matrix2 transposed (matrix2.T):")
print(matrix2.T)

#matrix2 = matrix2.T.T
print("\nHere is matrix2 transposed back (matrix2.T.T):")
print(matrix2.T.T)

# matrix2 = np.transpose(matrix2)
print("\nHere is matrix2 transposed with np.transpose(matrix2):")
print(np.transpose(matrix2))

# Transposing tensors
print("\nHere is tensor2 transposed (tensor2.T):")
print(tensor2.T)
print(tensor2.T.shape)



In NumPy, we can transpose matrices and tensors. For example, matrix2 can be transposed, using matrix2.T or numpy.transpose(matrix2)

Here is matrix2 transposed (matrix2.T):
[[1 5]
 [2 6]
 [3 7]
 [4 8]]

Here is matrix2 transposed back (matrix2.T.T):
[[1 2 3 4]
 [5 6 7 8]]

Here is matrix2 transposed with np.transpose(matrix2):
[[1 5]
 [2 6]
 [3 7]
 [4 8]]

Here is tensor2 transposed (tensor2.T):
[[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]]
(4, 2, 2)


In [5]:
#@title Transposition > PyTorch > Libs + Vars

import torch

print("In PyTorch, scalars, vectors and matrices belong to the class tensor.")

scalar3 = torch.tensor([1])
print("\n1. scalar3:")
print(scalar3)
print(type(scalar3), scalar3.shape)

vector3 = torch.tensor([ 1,2,3,4 ])
print("\n2. vector3:")
print(vector3)
print(type(vector3), vector3.shape)

matrix3 = torch.tensor([
    [1,2,3,4],
    [5,6,7,8]])

print("\n3. matrix3:")
print(matrix3)
print(type(matrix3), matrix3.shape)

tensor3 = torch.tensor([
    [[1,2,3,4],
     [5,6,7,8]],

    [[9,10,11,12],
     [13,14,15,16]]])
print("\n4. tensor3:")
print(tensor3)
print(type(tensor3), tensor3.shape)


In PyTorch, scalars, vectors and matrices belong to the class tensor.

1. scalar3:
tensor([1])
<class 'torch.Tensor'> torch.Size([1])

2. vector3:
tensor([1, 2, 3, 4])
<class 'torch.Tensor'> torch.Size([4])

3. matrix3:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
<class 'torch.Tensor'> torch.Size([2, 4])

4. tensor3:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]])
<class 'torch.Tensor'> torch.Size([2, 2, 4])


In [6]:
#@title Transposition > Pytorch

print("\nTransposing 1D tensors doesn't really do anything...")
vector3 = torch.tensor([ 1,2,3,4 ])
print("Untransposed:",vector3)
print("Transposed",vector3.T)

#print(type(vector3.T), vector3.T.shape)
print("\nFor this reason, we should create the vector as a 2D tensor from the start or reshape it, afterwards.")
print("So instead of this:")
print("vector3 = torch.tensor([ 1,2,3,4 ])", type(vector3), vector3.shape)
print("We could type this:")
print("vector3 = torch.tensor([[ 1,2,3,4 ]])",type(vector3), vector3.shape)
vector3 = torch.tensor([[ 1,2,3,4 ]]) # Instead of vector3 = torch.tensor([ 1,2,3,4 ])
print("Note the extra pair of brackets.")

print("\nNow, it can be transposed (vector3.T)")
print(vector3.T)
print(type(vector3.T), vector3.T.shape)
vector3 = torch.tensor([ 1,2,3,4 ]) # reset vector3

print("\nAnother way, is to reshape it like this:")
print("vector3 = vector3.reshape(1,4)")
vector3 = vector3.reshape(1,4)
print(vector3)
print("Note the extra set of brackets.")

vector3 = torch.tensor([ 1,2,3,4 ]) # reset vector3

print("\n...or reshape it like this:")
print("vector3 = vector3.reshape(-1,4)")
vector3 = vector3.reshape(-1,4)
print(vector3)
print("Note the extra set of brackets.")
print("\nNow, it can be transposed (vector3.T)")
print(vector3.T)
#print("In this case, you could also reshape from a row vector straight into a column vector (vector3.reshape(4,1))")
#print(vector3.reshape(4,1))
#print("As you can see, it looks as if it had been transposed.")
#print("However, this is a different operation and wont work with matrices or tensors...")

print("\nUsing .reshape you can even revert it back into a 1D tensor (vector3.reshape(-1))")
vector3 = torch.tensor([[ 1,2,3,4 ]]) # Instead of vector3 = torch.tensor([ 1,2,3,4 ])
print(vector3.reshape(-1))
print(type(vector3.reshape(-1)), vector3.reshape(-1).shape)

print("\nOn to algebraic matrices and tensors...")
print("\nHere is matrix3, a matrix or 2D tensor:")
print(matrix3)
print("\nLet's transpose it (matrix3.T)")
print(matrix3.T)
print(type(matrix3.T), matrix3.T.shape)

print("\nHere is tensor3, a 3D tensor:")
print(tensor3)
print("\nNow, let's transpose it (tensor3.T)")
print(tensor3.T)
print(type(tensor3.T), tensor3.T.shape)



Transposing 1D tensors doesn't really do anything...
Untransposed: tensor([1, 2, 3, 4])
Transposed tensor([1, 2, 3, 4])

For this reason, we should create the vector as a 2D tensor from the start or reshape it, afterwards.
So instead of this:
vector3 = torch.tensor([ 1,2,3,4 ]) <class 'torch.Tensor'> torch.Size([4])
We could type this:
vector3 = torch.tensor([[ 1,2,3,4 ]]) <class 'torch.Tensor'> torch.Size([4])
Note the extra pair of brackets.

Now, it can be transposed (vector3.T)
tensor([[1],
        [2],
        [3],
        [4]])
<class 'torch.Tensor'> torch.Size([4, 1])

Another way, is to reshape it like this:
vector3 = vector3.reshape(1,4)
tensor([[1, 2, 3, 4]])
Note the extra set of brackets.

...or reshape it like this:
vector3 = vector3.reshape(-1,4)
tensor([[1, 2, 3, 4]])
Note the extra set of brackets.

Now, it can be transposed (vector3.T)
tensor([[1],
        [2],
        [3],
        [4]])

Using .reshape you can even revert it back into a 1D tensor (vector3.reshape(-1)

/tmp/ipython-input-223499523.py:6: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  print("Transposed",vector3.T)


In [9]:
#@title Dot Product > NumPy

import numpy as np

# Dot product is the sum of the products (multiplications) of the corresponding entries of the two sequences of numbers.
# To break it down, the dot product is the sum of between two series of numbers, after each number in one sequence has been multipled with the corresponding number in the other sequence.

# You are given two different sequences if numbers.
# So, given two different sequence of numbers, you multiply each number from one sequence with the corresponding number from the other sequence.
# After that, you sum the product (what is left) of those multiplications.
# The result is one single number.

# The sequences need to be of the same lenght or dimensions.
# Typically, these sequences or series of numbers are vectors, matrices, tensors with the same number of elements and shape.

# Dot product may be used to reflect the commonalities between two objects, to tell how close/similar or how far/distinct things are from each other.

npvector1 = np.array([1,2,3,4])
npvector2 = np.array([0,1,0,-1])
npvector3 = [1,2,3,4,5,6]

# (1*0) + (2*1) + (3*0) + (4*(-1)) =
# 0 + 2 + 0 + -4 =
# -2

# Dot Product via Function
print("Function np.dot(a,b):", np.dot(npvector1,npvector2))

# Dot Product via calculation
print("Calculation np.sum(a*b):", np.sum(npvector1*npvector2))

# Slicing works and allows calculating objects with different sizes or shape to be calculated as if they had the same size and shape.
print("Slicing:", np.sum(npvector3[:4] * npvector2[:4] ))


Function np.dot(a,b): -2
Calculation np.sum(a*b): -2
Slicing: -2


In [86]:
#@title Matrix Multiplication > NumPy

import numpy as np

# In matrices, multiplication multiplies the rows of one matrix with the columns of another matrix.
# To multiply 2 different matrices, they need to have the appropriate dimensions.
# The inner dimensions need to match (have the same size)
# A 1 x 3 matrix can be multiplied with a 3 x 3 matrix or a 3 x 1 matrix.

# Matrix A is 1x3. Matrix B is 3x3. Matrix C is 3x1
arr1 = np.random.randint(10, size=(1,3))
arr2 = np.random.randint(10, size=(3,3))
arr3 = np.random.randint(10, size=(3,1))

#arr1 = np.random.randn(1,3) # for floats
#arr2 = np.random.randn(3,3) # for float
#arr3 = np.random.randn(3,1) # float

# Can you multiply matrices AC?
# 1x[3] [3]x1
# Inner dimension is on both is 3. They match. So they can be multiplied.

# Can you multiply matrices BA?
# 3x[3] [1]x3
# Inner dimensions are 3 and 1. They don't match. So they can't be multiplied.

# What would be the result of multiplying AB or AC?
# The result takes the shape of the outer dimensions.
# So, for matrices AB:
# [1]x3 x 3x[3]
# The result would be a 1 x 3 matrix.
print("Matrix A")
print(arr1)
print()
print("Matrix B")
print(arr2)
print("\nMultiplying matrices A and B via arr1@arr2")
arr1arr2 = arr1@arr2 # same as np.matmul(arr1,arr2)
print(arr1arr2)
print(type(arr1arr2), arr1arr2.shape)

# For matrices AC:
# [1]x3 x 3x[1]
# The result would be a 1 x 1 matrix.
print()
print("Matrix A")
print(arr1)
print()
print("Matrix C")
print(arr3)
print("\nMultiplying matrices A and C via np.matmul(arr1,arr3)")
arr1arr3 = np.matmul(arr1,arr3) # same as arr1@arr3
print(arr1arr3)
print(type(arr1arr3), arr1arr3.shape)



Matrix A
[[1 9 1]]

Matrix B
[[9 4 7]
 [8 8 4]
 [6 0 4]]

Multiplying matrices A and B via arr1@arr2
[[87 76 47]]
<class 'numpy.ndarray'> (1, 3)

Matrix A
[[1 9 1]]

Matrix C
[[2]
 [2]
 [9]]

Multiplying matrices A and C via np.matmul(arr1,arr3)
[[29]]
<class 'numpy.ndarray'> (1, 1)
