<a href="https://colab.research.google.com/github/Salciano/ShowcasePython/blob/main/Sandbox.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.array([1,2,3,4,5,6])

print(array * 3 )
print(array + 1 )
print(array ** 2)
print(np.round(array))


[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import pandas as panpy
import numpy as np

var0, var1 = 0, 1
var2 = 2
var3 = 3
var4 = 4
var10 = 0
var11 = 1
var20 = var10
var21 = var11

#var0, var1, var2 = var1, var0, var0

#swap()

print(var0, var1, var2)
print("..........2")

a = ['a', 'c', 'v', 's']
for i,v in enumerate(a, 1):
    print (i, v)

print(i)
print(v)
print(".....3")
str1, str2, str3 = "a", "b", "c"
print(str1, str2, str3)
print(str1 + str2 + str3)

print(".....4")
list1 = 0, 1, 2, 3
#list2 = drop
#list2 = 0, 1.1, "a", "4"

print("list1 b4 drop()", list1)
#panpy.drop(list[0])

print(list1)
#print(list2)

print(".....5")
lista = [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]
#lista = np.lista([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(type(lista), lista)


0 1 2
..........2
1 a
2 c
3 v
4 s
4
s
.....3
a b c
abc
.....4
list1 b4 drop() (0, 1, 2, 3)
(0, 1, 2, 3)
.....5
<class 'tuple'> ([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])
