<a href="https://colab.research.google.com/github/Salciano/Showpy/blob/main/Showcase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a brief showcase displaying practical basic coding skills that I developed autodidactically in Python.

In [16]:
#File reading and writting

with open("text.txt","w") as filey: #this creates a file called text.txt and assigns a variable to it called filey
  print("I like chocolate", file=filey) #this prints or writes to the file.


In [ ]:
# Rounding in python

# Python has a round() function that rounds numbers.
print(round(1,123456789))

# It is possible to round a number to a specific decimal place/digit.
print(round(1.123456789, 5)) # In this case, it rounded to 5 decimal digits, the 5th decimal place.

print("\u2500" * 50)
# Python rounds even numbers down and odd numbers up
print("Unrounded Numbers ≈ Rounded Numbers")
i = 1.5
while i <= 20:
  print(i, end = " ≈ ")
  print(round(i))
  i += 1

print("\u2500" * 50)
# Python automatically assigns data types according to the result.
# For example: whole numbers are assigned as integers; while decimal numbers are assigned as floats.
# This even converts already existing data to different data types.

print("Rounding may change data type:")
x = round(2.55)
print(x, type(x)) # Python stored the rounded number as an integer data type.
x = round(2.55, 1)
print(x, type(x)) # Python converted the rounded number into a float, which was previously an integer.
x = round(2.55)
print(x, type(x)) # Python converted the rounded float back into an integer.
# This was done using the same variable and without declaring it or its data type, in the first place.
# So, in Python, you don't need to declare variables. Also, variables can change its data type after creation and being assigned a data type.

print("\u2500" * 50)
# Here is how to round lists
listy = [ 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5 ]
print("Let's try printing a list. Note the square brackets, when printing lists without formatting.")
print(listy)
roundylisty = [ round(i) for i in listy ]
print("This is how a rounded list looks like. Note the square brackets, when printing lists without formatting.")
print(roundylisty)
# print(round(listy)) This would not work. You need to round each element individually.
print("Let's try printing a tupple. Note the round brackets, when printing lists without formatting.")
listy = ( 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5 )
print(listy)
roundylisty = ( round(i) for i in listy ) # tuples are immutable. So we can't round it after values have been assigned to it.
print("This is how a rounded tupple looks like. Note the square brackets, when printing lists without formatting.")
print(roundylisty)
print("Let's try printing a set. Note the curl brackets, when printing lists without formatting.")
listy = { 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5 }
print(listy)
print("This is how a rounded set looks like. Note the square brackets, when printing lists without formatting. Very important to note that there was data loss or data cleaning, because sets are unique and cannot have duplicate values.")
roundylisty = { round(i) for i in listy }
print(roundylisty)
print("Data type was changed. Even for the tupple. Only the values themselves are immutable, but the data type itself can be changed.")

1
1.12346
──────────────────────────────────────────────────
Unrounded Numbers ≈ Rounded Numbers
1.5 ≈ 2
2.5 ≈ 2
3.5 ≈ 4
4.5 ≈ 4
5.5 ≈ 6
6.5 ≈ 6
7.5 ≈ 8
8.5 ≈ 8
9.5 ≈ 10
10.5 ≈ 10
11.5 ≈ 12
12.5 ≈ 12
13.5 ≈ 14
14.5 ≈ 14
15.5 ≈ 16
16.5 ≈ 16
17.5 ≈ 18
18.5 ≈ 18
19.5 ≈ 20
──────────────────────────────────────────────────
Rounding may change data type:
3 <class 'int'>
2.5 <class 'float'>
3 <class 'int'>
──────────────────────────────────────────────────
Let's try printing a list. Note the square brackets, when printing lists without formatting.
[1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5]
This is how a rounded list looks like. Note the square brackets, when printing lists without formatting.
[2, 2, 4, 4, 6, 6, 8, 8, 10, 10]
Let's try printing a tupple. Note the round brackets, when printing lists without formatting.
(1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5)
This is how a rounded tupple looks like. Note the square brackets, when printing lists without formatting.
<generato

In [ ]:
# Rounding Libraries
# It is also possible to use the numpy library for rounding

import numpy as np

array = np.array([[1.5,2.5,3.5,4.5,5.5], [6.5,7.5,8.5,9.5,10.5]])

print("You'd like me to round these numbers?")
print(array)
print("I'm very odd at rounding numbers, but lemme try! Even numbers are oddly rounded down. Odd numbers are normally rounded up. Did I do it right?")
print(np.round(array))

#print(round(array)) does not work in native Python. That is one reason to use numpy.

# Additionally, you can also truncate in Numpy. Note that numpy returns floats
print("Numpy: Untruncated Numbers ≈ Truncated Numbers")
i = 1.5
while i < 11:
  print(i, end = " ≈ ")
  print(np.trunc(i))
  i += 1
print()

# Additionally, you can also truncate in Math. Note that math returns integers
print("Math: Untruncated Numbers ≈ Truncated Numbers")
i = 1.5
while i < 11:
  print(i, end = " ≈ ")
  print(math.trunc(i))
  i += 1
print()

# Furthermore, it is possible to round down or up.
print("Math: Unfloored Numbers ≈ Floored (Rounded Down) Numbers")
i = 1.5
while i < 11:
  print(i, end = " ≈ ")
  print(math.floor(i))
  i += 1
print()

print("Math: Unceiled Numbers ≈ Ceiled (Rounded Up) Numbers")
i = 1.5
while i < 11:
  print(i, end = " ≈ ")
  print(math.ceil(i))
  i += 1
print()


print (math.floor(3.5)) # floor
print (math.trunc(3.5)) # work as floor
print (math.ceil(3.5))  # ceil

In [ ]:
# Functions for Geometry
# It is possible to use libraries: numpy or math
import numpy
import math

# These libraries have the constant pi, π

print("Numpy: This is the value of π:", numpy.pi)
print(" Math: This is the value of π:", math.pi)
# Native has no pi :(
# print("Native: This is the value of π:", pi)

# You can use pi to calculate the area, diameter or a radius of circle.
perimeter = 5 # Lets say we have a circle with 5cm perimeter.

# To calculate the radius

# To calculate the diameter

# To calculate the area
radius = 5 # Lets say we have a circle with 5cm radius.
area = math.pi * radius ** 2

print( "Numpy: A circle with a radius of", radius, "cm has an area of:", area, "cm2.")

area = numpy.pi * radius ** 2
print( " Math: A circle with a radius of", radius, "cm has an area of:", area, "cm2.")

print()
# To calculate the area of several circles in an array/list
radii = np.array([1,2,3,4,5])
print("Here we have", len(radii), "circles. Each with a radius of:")
# print(radii) # with brackets
#print(*radii, sep="cm, ", end = "cm") # without brackets
for i in range(len(radii)):
    print(f"Circle {i+1}: {radii[i]} cm.")

print("\nHere is the calculated area for each circle:")
area = np.pi * radii ** 2
#print(np.pi * radii ** 2 ) # Result in ugly brackets and without using area variable
#print(*area, sep = ", ") # Result separated by commas in a single line

for i in range(len(radii)):
    print(f"Circle {i+1}> Radius: {radii[i]} cm. Area: {area[i]} cm2")


In [ ]:
import numpy as np

np.array([1,2,3,4,5,6])

print(array * 3 )
print(array + 1 )
print(array ** 2)
print(np.round(array))


[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import pandas as panpy
import numpy as np

var0, var1 = 0, 1
var2 = 2
var3 = 3
var4 = 4
var10 = 0
var11 = 1
var20 = var10
var21 = var11

#var0, var1, var2 = var1, var0, var0

#swap()

print(var0, var1, var2)
print("..........2")

a = ['a', 'c', 'v', 's']
for i,v in enumerate(a, 1):
    print (i, v)

print(i)
print(v)
print(".....3")
str1, str2, str3 = "a", "b", "c"
print(str1, str2, str3)
print(str1 + str2 + str3)

print(".....4")
list1 = 0, 1, 2, 3
#list2 = drop
#list2 = 0, 1.1, "a", "4"

print("list1 b4 drop()", list1)
#panpy.drop(list[0])

print(list1)
#print(list2)

print(".....5")
lista = [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]
#lista = np.lista([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(type(lista), lista)



0 1 2
..........2
1 a
2 c
3 v
4 s
4
s
.....3
a b c
abc
.....4
list1 b4 drop() (0, 1, 2, 3)
(0, 1, 2, 3)
.....5
<class 'tuple'> ([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])


In [ ]:

import numpy as np

# leading zeroes dont work, but you can ident, somehow. i thought identation was important in py
# dont know why the square brackets are printed...
array = np.array([
    [  1,  2,  3,  4],
     [ 5,  6,  7,  8],
      [9, 10, 11, 12]])

print(array)
print(type(array))
# slice and dice
print(array[0:2, 0:2])






[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
[[1 2]
 [5 6]]
