<a href="https://colab.research.google.com/github/Salciano/ShowcasePython/blob/main/ShowPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a brief showcase, displaying practical basic coding skills that I developed autodidactically in Python.

In [ ]:
print("Arithmetic/Algebraic Operators") # Operators are things/token/symbols that act/operate on other things/operands

a, b = 10, 5
print(f"{a} + {b} = {a + b}      > Addition")
print(f"{a} - {b} = {a - b}       > Subtraction")
print(f"{a} * {b} = {a * b}      > Multiplication")
print(f"{a} / {b} = {a / b}     > Division (Float)")

print()
time1, clock12 = 18, 12
runtime1, clock24 = 100, 24
print(f"{a} ** {b} = {a ** b} > Exponentiation (10 to the power of 5) or (10*10*10*10*10) or (10^5)")
print(f"{a} // {b} = {a // b}      > Floor Division (the number a times a number fits tidly into another)")
print(f"{a} % {b} = {a % b}       > Modulus (remainder or difference after dividing 10 by 5)")

print("\nPractical Uses")
print("Floor division can be useful for counting time.")
print(f"For example, let's say, I have been playing a game for {runtime1} hours. Using this operator, it is possible to calculate that I have been playing the game for {runtime1 // clock24} days (and {runtime1 - (clock24*(runtime1 // clock24))} hours). {runtime1} // {clock24} = {runtime1 // clock24}. Maybe I should take a break :)")
print(f"Another example, let's say, I have been training Calisthenics for 45 days and each month has 30 days. Then, I have been training for {45 // 30} month(s).")
print(f"Lastly, let's say, I have been training martial arts for 200 months and each year has 12 months. Then, I have been training for {200 // 12} year(s). Pretty long time!")

print("\nModulus is also useful for counting time. Namely for clocks, which wrap around every 12 or 24 hours (12am vs 12pm vs 24h).")
print(f"For example, let's say, it is 18:00 on a {clock24} hour clock. On an {clock12} hour clock, it is {time1 % clock12}pm. {time1} % {clock12} = {time1 % clock12}")


Arithmetic/Algebraic Operators
10 + 5 = 15      > Addition
10 - 5 = 5       > Subtraction
10 * 5 = 50      > Multiplication
10 / 5 = 2.0     > Division (Float)

10 ** 5 = 100000 > Exponentiation (10 to the power of 5) or (10*10*10*10*10) or (10^5)
10 // 5 = 2      > Floor Division (the number a times a number fits tidly into another)
10 % 5 = 0       > Modulus (remainder or difference after dividing 10 by 5)

Practical Uses
Floor division can be useful for counting time.
For example, let's say, I have been playing a game for 100 hours. Using this operator, it is possible to calculate that I have been playing the game for 4 days (and 4 hours). 100 // 24 = 4. Maybe I should take a break :)
Another example, let's say, I have been training Calisthenics for 45 days and each month has 30 days. Then, I have been training for 1 month(s).
Lastly, let's say, I have been training martial arts for 200 months and each year has 12 months. Then, I have been training for 16 year(s). Pretty long time!


In [ ]:
#print("File Processing")

#reading and writting

with open("text.txt","w") as filey: #this creates a file called text.txt and assigns a variable to it called filey
  print("I like chocolate", file=filey) #this prints or writes to the file.


In [ ]:
# Rounding in python

# Python has a round() function that rounds numbers.
print(round(1,123456789))

# It is possible to round a number to a specific decimal place/digit.
print(round(1.123456789, 5)) # In this case, it rounded to 5 decimal digits, the 5th decimal place.

print("\u2500" * 50)
# Python rounds even numbers down and odd numbers up
print("Unrounded Numbers ≈ Rounded Numbers")


i = 1.5
while i < 11:
    print( i, "≈", round(i), "\t|", i+10, "≈", round(i+10))
    i += 1

print("\u2500" * 50)
print("Usually (not always), Python automatically assigns data types according to the result. Values inside arrays (NumPy library) may remain floats.")
print("For example: whole numbers are assigned as integers; while decimal numbers are assigned as floats.")
print("This even converts already existing data to different data types.")

print("\nRounding may change data type! Let's round 2.55 and see what happens:")
x = round(2.55)
print("x = round(2.55) ≈", x, type(x), "Python stored the rounded number as an integer data type.")
x = round(2.55, 1)
print("x = round(2.55, 1) ≈", x, type(x), "Python converted the rounded number into a float, which was previously an integer.")
x = round(2.55)
print("x = round(2.55) ≈", x, type(x), "Python converted the rounded float back into an integer.")
print("This was done using the same variable and without declaring it or its data type, in the first place.")
print("So, in Python, you don't need to declare variables. Also, variables can change its data type after creation and being assigned a data type.")

print("\nThis even works without variables. Let's round 2.55 without storing it in a variable and see what happens:")
print("round(2.55) ≈", round(2.55), type(round(2.55)), "Python stored the rounded number as an integer data type.")
print("round(2.55, 1) ≈", round(2.55, 1), type(round(2.55, 1)), "Python converted the rounded number into a float, which was previously an integer.")
print("round(2.55) ≈", round(2.55), type(round(2.55)), "Python converted the rounded float back into an integer.")

print("\u2500" * 50)
# Here is how to round lists
listy = [ 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5 ]
print("Let's try printing a list. Note the square brackets, when printing lists without formatting.")
print(listy)
roundylisty = [ round(i) for i in listy ]

print("\nThis is how a rounded list looks like. Note the square brackets, when printing lists without formatting.")
print(roundylisty)
# print(round(listy)) This would not work. You need to round each element individually.

print("\nLet's try printing a tupple. Note the round brackets, when printing lists without formatting.")
listy = ( 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5 )
print(listy)
#roundylisty = ( round(i) for i in listy ) # tuples are immutable. So we can't round it after values have been assigned to it.

print("\nThis is how a rounded tupple looks like. Note the square brackets, when printing lists without formatting.")
print(roundylisty)

print("\nLet's try printing a set.")
listy = { 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5 }
print(listy)
print("Note the curl brackets, when printing lists without formatting.")

print("\nThis is how a rounded set looks like.")
roundylisty = { round(i) for i in listy }
print(roundylisty)
print("Note the curly brackets, when printing lists without formatting.")
print("More importantly, note that there was data loss or data cleaning, because data sets are unique and cannot have duplicate values. Be very careful when rounding sets!")

print("\nIn conclusion, data types were changed. Even for the tupple. Only the values themselves are immutable, but the data type of the structure itself can be changed.")

1
1.12346
──────────────────────────────────────────────────
Unrounded Numbers ≈ Rounded Numbers
1.5 ≈ 2 	| 11.5 ≈ 12
2.5 ≈ 2 	| 12.5 ≈ 12
3.5 ≈ 4 	| 13.5 ≈ 14
4.5 ≈ 4 	| 14.5 ≈ 14
5.5 ≈ 6 	| 15.5 ≈ 16
6.5 ≈ 6 	| 16.5 ≈ 16
7.5 ≈ 8 	| 17.5 ≈ 18
8.5 ≈ 8 	| 18.5 ≈ 18
9.5 ≈ 10 	| 19.5 ≈ 20
10.5 ≈ 10 	| 20.5 ≈ 20
──────────────────────────────────────────────────
Usually (not always), Python automatically assigns data types according to the result. Values inside arrays (NumPy library) may remain floats.
For example: whole numbers are assigned as integers; while decimal numbers are assigned as floats.
This even converts already existing data to different data types.

Rounding may change data type! Let's round 2.55 and see what happens:
x = round(2.55) ≈ 3 <class 'int'> Python stored the rounded number as an integer data type.
x = round(2.55, 1) ≈ 2.5 <class 'float'> Python converted the rounded number into a float, which was previously an integer.
x = round(2.55) ≈ 3 <class 'int'> Python con

In [ ]:
# Rounding Libraries
# It is also possible to use libraries, like numpy or math. Although math lacks math.round()

import numpy as np
import math

array = np.array([[1.5,2.5,3.5,4.5,5.5], [6.5,7.5,8.5,9.5,10.5]])

print("You'd like me to round these numbers?")
print(array)
print("I'm very odd at rounding numbers, but lemme try! Even numbers are oddly rounded down. Odd numbers are normally rounded up. Is this right?")
print(np.round(array))
print("Note the rounded data type inside the array is still float, despite looking like integers: type(np.round(array[0,0])) =", type(np.round(array[0,0])))

#print(round(array)) does not work in native Python. That is one reason to use numpy.

# Additionally, you can also truncate in Numpy. Note that numpy returns floats
print("\nNumpy: Untruncated Numbers ≈ Truncated Numbers (numpy.trunc)")
i = 1.5
while i < 6:
  print(i, end = " ≈ ")
  print(np.trunc(i), type(np.trunc(i)))
  i += 1
print()

# Additionally, you can also truncate in Math. Note that math returns integers
print("Math: Untruncated Numbers ≈ Truncated Numbers (math.trunc)")
i = 1.5
while i < 6:
  print(i, end = " ≈ ")
  print(math.trunc(i), type(math.trunc(i)))
  i += 1
print()

# Furthermore, it is possible to round down or up.
print("Math: Unfloored Numbers ≈ Floored (Rounded Down) Numbers (math.floor)")
i = 1.5
while i < 6:
  print(i, end = " ≈ ")
  print(math.floor(i))
  i += 1
print()

print("Math: Unceiled Numbers ≈ Ceiled (Rounded Up) Numbers (math.ceil)")
i = 1.5
while i < 11:
  print(f"{i} ≈ {math.ceil(i):02d}\t| {i+1} ≈ {math.ceil(i+1):02d}")
  i += 2


You'd like me to round these numbers?
[[ 1.5  2.5  3.5  4.5  5.5]
 [ 6.5  7.5  8.5  9.5 10.5]]
I'm very odd at rounding numbers, but lemme try! Even numbers are oddly rounded down. Odd numbers are normally rounded up. Is this right?
[[ 2.  2.  4.  4.  6.]
 [ 6.  8.  8. 10. 10.]]
Note the rounded data type inside the array is still float, despite looking like integers: type(np.round(array[0,0])) = <class 'numpy.float64'>

Numpy: Untruncated Numbers ≈ Truncated Numbers (numpy.trunc)
1.5 ≈ 1.0 <class 'numpy.float64'>
2.5 ≈ 2.0 <class 'numpy.float64'>
3.5 ≈ 3.0 <class 'numpy.float64'>
4.5 ≈ 4.0 <class 'numpy.float64'>
5.5 ≈ 5.0 <class 'numpy.float64'>

Math: Untruncated Numbers ≈ Truncated Numbers (math.trunc)
1.5 ≈ 1 <class 'int'>
2.5 ≈ 2 <class 'int'>
3.5 ≈ 3 <class 'int'>
4.5 ≈ 4 <class 'int'>
5.5 ≈ 5 <class 'int'>

Math: Unfloored Numbers ≈ Floored (Rounded Down) Numbers (math.floor)
1.5 ≈ 1
2.5 ≈ 2
3.5 ≈ 3
4.5 ≈ 4
5.5 ≈ 5

Math: Unceiled Numbers ≈ Ceiled (Rounded Up) Numbers (math.cei

In [ ]:
# Geometric Functions
import numpy as np
import math

print("Even though Python lacks the constant π (pi), there are Python libraries that include it, like NumPy or Math.")
print("In numpy, it stored as numpy.pi.  π =", numpy.pi, type(numpy.pi))
print("In math, it is stored as math.pi. π =", math.pi, type(math.pi))
# print("Native has no π :(", pi)

print("\nPi is useful to calculate things, like a circle's radius, diameter, circumference.")

# Radius
print("\nTo calculate the radius:")
circumference = 5 # Lets say we have a circle with 5cm circumference.
print(f"Numpy: A circle with a circumference of {circumference} cm has a radius of: {circumference / (2 * numpy.pi)} cm. (circumference / (2 * numpy.pi))")
print(f" Math: A circle with a circumference of {circumference} cm has a radius of: {circumference / (2 * math.pi)} cm. (circumference / (2 * math.pi))")

# Diameter
print("\nTo calculate the diameter:")
circumference = 5 # Lets say we have a circle with 5cm circumference, again. Might want to change value, later.
print(f"Numpy: A circle with a circumference of {circumference} cm has a diameter of: {circumference / numpy.pi} cm. (perimeter / numpy.pi)")
print(f" Math: A circle with a circumference of {circumference} cm has a diameter of: {circumference / math.pi} cm. (perimeter / math.pi)")

# Circumference/Perimeter
print("\nTo calculate the circumference or perimeter of a circle:")
radius = 5 # Lets say we have a circle with 5cm radius.
print(f"Numpy: A circle with a radius of {radius} cm has a circumference of: {2 * numpy.pi * radius} cm. (2 * numpy.pi * radius)")
print(f" Math: A circle with a radius of {radius} cm has a circumference of: {2 * numpy.pi * radius} cm. (2 * math.pi * radius)")

# Area
print("\nTo calculate the area:")
radius = 5 # Lets say we have a circle with 5cm radius, again. Might want to change value, later
area = math.pi * radius ** 2

print( "Numpy: A circle with a radius of", radius, "cm has an area of:", area, "cm2.")
area = np.pi * radius ** 2
print( " Math: A circle with a radius of", radius, "cm has an area of:", area, "cm2.")

print()
# To calculate the area of several circles in an array/list
radii = np.array([1,2,3,4,5])
print("Here we have", len(radii), "circles. Each with a radius of:")
# print(radii) # with brackets
#print(*radii, sep="cm, ", end = "cm") # without brackets
for i in range(len(radii)):
    print(f"Circle {i+1}: {radii[i]} cm.")

print("\nHere is the calculated area for each circle:")
area = np.pi * radii ** 2
#print(np.pi * radii ** 2 ) # Result in ugly brackets and without using area variable
#print(*area, sep = ", ") # Result separated by commas in a single line

for i in range(len(radii)):
    print(f"Circle {i+1}> Radius: {radii[i]} cm. Area: {area[i]} cm2")


Even though Python lacks the constant π (pi), there are Python libraries that include it, like NumPy or Math.
In numpy, it stored as numpy.pi.  π = 3.141592653589793 <class 'float'>
In math, it is stored as math.pi. π = 3.141592653589793 <class 'float'>

Pi is useful to calculate things, like the radius, diameter, circumference or area of a circle.

To calculate the radius:
Numpy: A circle with a circumference of 5 cm has a radius of: 0.7957747154594768 cm. (circumference / (2 * numpy.pi))
 Math: A circle with a circumference of 5 cm has a radius of: 0.7957747154594768 cm. (circumference / (2 * math.pi))

To calculate the diameter, without the radius
Numpy: A circle with a circumference of 5 cm has a diameter of: 1.5915494309189535 cm. (perimeter / numpy.pi)
 Math: A circle with a circumference of 5 cm has a diameter of: 1.5915494309189535 cm. (perimeter / math.pi)

To calculate the circumference or perimeter of a circle:
Numpy: A circle with a radius of 5 cm has a circumference of: 31

In [6]:
# Slicing
import numpy as np

# leading zeroes dont work, but you can ident, somehow. wasn't identation important in py?
# square brackets are printed... To remove them, unpack with "*" or convert to string. reconvert if needed...
arry = np.array([
    [  1,  2,  3,  4],
     [ 5,  6,  7,  8],
      [9, 10, 11, 12]])

print("Hello! Meet arry. Arry is an array that looks like this:")
print(arry)
print(f"{type(arry)} <shape/dimenions: {arry.shape}>")
print("\nWe can slice arry, like a cake, using: variable[y1:y2, x1:x2, step].")
print("\nSlicing first 2 rows and columns > arry[0:2, 0:2]:")
print(arry[0:2, 0:2]) # slice and dice
print("\nSlicing last 2 rows and colums > arry[1:3, 2:4]:")
print(arry[1:3, 2:4]) # slice and dice


Hello! Meet arry. Arry is an array that looks like this:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'> <shape/dimenions: (3, 4)>

We can slice arry, like a cake, using: variable[y1:y2, x1:x2, step].

Slicing first 2 rows and columns > arry[0:2, 0:2]:
[[1 2]
 [5 6]]

Slicing last 2 rows and colums > arry[1:3, 2:4]:
[[ 7  8]
 [11 12]]
